apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - http: nginx-stack.local
      # frontend -> "/"
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      # Backend -> "/api"
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000
